version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: formsio-ci-web:latest
    ports:
      - "0.0.0.0:3000:3000"
    networks:
      - test-network
    volumes:
      - ./src:/app/src:z
    command: npm run dev

  cypress:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: formsio-ci-cypress:latest
    depends_on:
      - web
    volumes:
      - ./cypress:/app/cypress:z
    networks:
      - test-network

networks:
  test-network:
    driver: bridge